apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kubeflow
  name: mlflow-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage   
